name: Java CI
on:
  - push
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 25101988Jjj
          MYSQL_DATABASE: ticket_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=30s

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h localhost -P 3306 -u root -p25101988Jjj --silent 2>/dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

      # Компіляція перед тестами - це важливо!
      - name: Compile project
        run: mvn --batch-mode clean compile test-compile

      - name: Run tests
        run: mvn --batch-mode test
        env:
          MAVEN_OPTS: "-Xmx512m"

      - uses: mate-academy/auto-approve-action@v2
        if: ${{ github.event.pull_request && success() }}
        with:
          github-token: ${{ github.token }}

      - uses: mate-academy/auto-reject-action@v2
        if: ${{ github.event.pull_request && failure() }}
        with:
          github-token: ${{ github.token }}