name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ticket_app
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          --health-start-period=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent 2>/dev/null; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done

      - name: Set up application config
        run: |
          echo "spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ticket_app" > src/main/resources/application-ci.properties
          echo "spring.datasource.username=root" >> src/main/resources/application-ci.properties
          echo "spring.datasource.password=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> src/main/resources/application-ci.properties

      - name: Clean and compile with debug info
        run: mvn clean compile -X -e

      - name: Compile test classes
        run: mvn test-compile -X -e

      - name: Run tests without fork
        run: mvn test -Dsurefire.forkCount=0 -X -e
        env:
          MAVEN_OPTS: -Xmx1024m

      - name: Auto-approve PR if successful
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: mate-academy/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-reject PR if failed
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: mate-academy/auto-reject-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}